export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";
export const FAVOURITE="FAVOURITE";
export const SET_CATEGORY="SET_CATEGORY";
export const SET_FILTERED_PRODUCTS="SET_FILTERED_PRODUCTS";
export const SET_PRICE_FILTER="SET_PRICE_FILTER";
export const CLEAR_CART="CLEAR_CART";
